### ISSUE TITLE
아 코세라.. 공부 마무리 해야하는데 언제 다시 시작하지 ㅋ

### ISSUE THREAD

**Issue by phh0606c** [ml-mate/coursera-machine-leaning#18]
지금 하둡 에코 시스템 공부하고 있는데 올해까지 계속 공부할 기세 .. 
하둡 에코 시스템 공부할게 어마어마하게 많구나 ㄷㄷ 
하둡부터 마스터 하고  난뒤에 모델링 쪽을 다시 봐야할거 같은데.. 

그때되면 모델링 쪽도 백지 상태로 다시 시작해야할 듯.. 
내년에 봬요

**Comment by joonsun-baek** [comment]
댓글을 언제달았지
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

다시 시작하면 말해줘

앤드류응의 DeepLearning도 한번 갑시다

**Comment by phh0606c** [comment]
ㅋㅋㅋㅋㅋ 갑시다 내가 진짜 ㅋㅋ 숨통 트이기만 해 아주 그냥 빡공부 간다 ㅋㅋㅋㅋ 
이제서야 이걸 배우면 무엇을 할 수 있을지, 어떻게 내가 뭘 해야하는지 조금 보이는거 같소이다.

**Comment by cartoon1110** [comment]
RIGHT NOW

**Comment by phh0606c** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 가즈아 !
