### ISSUE TITLE
2년지나서 까먹었는데 다시 시작할래요

### ISSUE THREAD

**Issue by rladowl92** [ml-mate/coursera-machine-leaning#20]
지금쯤이면 번역 다 추가됐겠죠..?

**Comment by rladowl92** [comment]
![Screenshot_20210129-011450_Coursera](https://user-images.githubusercontent.com/36468143/106166373-71c82a00-61cf-11eb-92fc-88b51eb33772.jpg)
마지막 강의까지 한글자막 추가완료!

**Comment by phh0606c** [comment]
@rladowl92 
크 웰컴이지 완전 ㅋㅋㅋㅋㅋ 이번엔 우리 끝까지 같이 가보자
나도 번역 된거 확인하고 고고띵 다시 하기로 마음 먹음

**Comment by cartoon1110** [comment]
오 그럼 애지도 [매주 인증 스터디](https://github.com/ml-mate/coursera-machine-leaning/issues/19) 룰에 참가하시겠습니까?
